version: '3'

services:
  bot:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MONGO_URL: 'mongodb://db/bot'
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - ./.docker/mongo/db:/data/db
